[project]
name = 'Tokenized-Telecommunications-5G-Network-Optimization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bandwidth-allocation]
path = 'contracts/bandwidth-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.edge-computing]
path = 'contracts/edge-computing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
